before_install:
  - gem update bundler
language: ruby
rvm:
- 2.2.5
- 2.3.1
gemfile:
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
